# Generated by Django 3.2.3 on 2021-05-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_subs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='subs',
        ),
    ]
