# Generated by Django 3.2.3 on 2021-05-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=500)),
                ('release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('movie_genre', models.TextField(blank=True, max_length=10000, null=True)),
                ('movie_popularity', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_rating', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_trailer', models.CharField(blank=True, max_length=5000, null=True)),
                ('storyline', models.TextField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('movie_director', models.CharField(blank=True, max_length=200, null=True)),
                ('movie_actor1', models.CharField(blank=True, max_length=1000, null=True)),
                ('movie_actor2', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_actor3', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_actor4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
