# Generated by Django 3.2.3 on 2021-05-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
